logging:
  config: classpath:logback-dev.xml
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080

